version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prompt-enhancer
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ANTHROPIC_API_KEY=xxxx
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CODEGEN_API_KEY=${CODEGEN_API_KEY}
      - CODEGEN_ORG_ID=${CODEGEN_ORG_ID}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_WEBHOOK_TOKEN=${N8N_WEBHOOK_TOKEN}
    volumes:
      - prompt-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  prompt-data:
    driver: local