name: Voyager Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Voyager Codex Review
        uses: VOYAGER-Inc/voyager_codex@v1
        with:
          codegen_api_key: ${{ secrets.CODEGEN_API_KEY }}
          codegen_org_id: ${{ secrets.CODEGEN_ORG_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN || github.token }}
