on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Code Review with Voyager
        uses: voyager-codegen/voyager-codex@v1
        with:
          codegen_api_key: ${{ secrets.CODEGEN_API_KEY }}
          codegen_org_id: ${{ secrets.CODEGEN_ORG_ID }}
